import type { Metadata } from "next";
import Link from 'next';
import useRouter from 'next';
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from './components/NavBar'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="px-12 h-screen w-auto bg-blue-200 overflow-y-scroll">
          <NavBar />
          {children}
        </div>
      </body>
    </html >
  );
}
