import type { Metadata } from "next";
import Link from 'next';
import useRouter from 'next';
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from './components/NavBar'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-auto overflow-y-scroll bg-4848 bg-gradient-to-tr from-black">
          <div className="px-12 py-2 w-screen">
            <NavBar />
          </div>
          {children}
        </div>
      </body>
    </html >
  );
}
